kind: Pod
apiVersion: v1
metadata:
  name: webapp
spec:
  containers:
  - image: jweissig/app:0.0.1
    name: webapp
    env:
    - name: DB_PASSWORD
      value: password 
    - name: DB_USERNAME
      value: username
    
#       valueFrom:
#         secretKeyRef:
#           name: example-secret
#           key: password

#value: <path:secret/data/creds#password> 
#value: <path:secret/data/avp#username> 
